### ISSUE TITLE
FileNotFoundException in Windows

### ISSUE THREAD

**Issue by lachmart** [nepada/bust-cache#60]
src/BustCache/FileSystem/LocalFileSystem.php:55
![image](https://user-images.githubusercontent.com/7383506/185147149-9ecc9a69-3957-4e8b-bad5-117493e01d52.png)

That forward slash does not work for windows paths and exception prints text without realpath()
Exception:
File 'D:\www\project\www/FrontModule/dist/app.css' is outside of allowed base directory 'D:\www\project\www'
Realpath comparison which fails:
str_starts_with('D:\www\project\www\FrontModule\dist\app.css', 'D:\www\project\www/')

**Comment by jvitasek** [comment]
+1, this happens on Windows, on Linux it's OK

**Comment by xificurk** [comment]
Would any one of you be able to send PR with a fix? I don't really use Windows on any of my environments and CI in current setup does not cover it either. If this is really the only problematic place, it should be as simple as switching `'/'` -> `DIRECTORY_SEPARATOR`.
